version: "3.8"
services:
  giphy-ui-project:
    build: .
    container_name: giphy-ui-project_c
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
